---
version: '3.5'
services:
  nginx:
    container_name: nginx-sni
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    extra_hosts:
      - "fritz.is.here:127.0.0.1"
      - "buy.it:127.0.0.1"
      - "google.it:127.0.0.1"
      - "git.hub:127.0.0.1"
    networks:
      - backend
  # sni-client:
  #   container_name: sni-client
  #   image: alpine:3.17
  #   depends_on:
  #     - nginx
  #   extra_hosts:
  #     - "fritz.is.here:127.0.0.1"
  #     - "buy.it:127.0.0.1"
  #     - "google.it:127.0.0.1"
  #     - "git.hub:127.0.0.1"
  #   networks:
  #     - backend
  #   command: >
  #   sh -c "apk add curl
  #   && python manage.py runserver 0.0.0.0:8000"
    
networks:
  backend:
  